###
POST http://localhost:3000/permissions_roles
Content-Type: application/json

{
  "role": "Pastor Presidente",
  "permissions": ["manage_churches", "manage_data", "manage_designations", "manage_sectors"]
}


###
DELETE http://localhost:3000/roles/40bf4deb-3435-4994-a48c-bb0a1f99b967

###